name: flutter_amap_workspace
publish_to: none

environment:
  sdk: ">=3.12.0 <4.0.0"

workspace:
  - packages/flutter_amap
  - packages/flutter_amap/example
  - packages/flutter_amap_navi
  - packages/flutter_amap_navi/example
  - example
